### ISSUE TITLE
Could not find module `@ember/application/deprecations`

### ISSUE THREAD

**Issue by amiarSlimane** [prysmex/ember-eui#161]
```
ember -v
ember-cli: 4.1.1
node: 16.14.2
os: linux x64
```
```
 // package.json 
 "ember-cli": "~4.1.1",
 "ember-source": "~4.1.0",
"@ember-eui/core": "^5.10.0",
```

using  EuiConfirmModal i get the following error message

```
Error occurred:

- While rendering:
  -top-level
    application
      admin
        admin.stores
          admin.stores.index
            eui-confirm-modal
              eui-modal
                eui-overlay-mask

```

 `Uncaught (in promise) Error: Could not find module '@ember/application/deprecations' imported from'(require)'`

**Comment by amiarSlimane** [comment]
I have created a new project and it is working , i will check which dependency is causing this issue

**Comment by amiarSlimane** [comment]
now i have another issue, using ember 4.5.0  i get `Uncaught Error: Assertion Failed: You attempted to overwrite the built-in helper "unique-id" which is not allowed. Please rename the helper.`

**Comment by amiarSlimane** [comment]
i found that ember-cli-notifications is causing this problem , when i have removed this dependency it works.
is this issue caused by ember-cli-notifications or ember-eui

**Comment by betocantu93** [comment]
Interesting, I'm not sure to be honest, maybe trying to update ember cli notifications or something 🤔 .
