### ISSUE TITLE
Compatibility with ember 4.4+

### ISSUE THREAD

**Issue by nanuxbe** [prysmex/ember-eui#162]
Hello and thanks for the great work.

The `unique-id` helper was introduced in ember 4.4.0. As a result, trying to use @ember-eui/core produces the following error:

``` 
index.js:181 Uncaught Error: Assertion Failed: You attempted to overwrite the built-in helper "unique-id" which is not allowed. Please rename the helper.
    at assert (index.js:181:1)
```
I have tried to take a look and simply remove the helper but it would appear it is an integral aprt of the project.

Any idea on how to fix this?

**Comment by betocantu93** [comment]
Hello! Good catch and question, I think we could add the unique id polyfill so people with say 3.28 stills gets the helper through it, _but_ if I remember correctly we also use it on JS. Not sure if the RFC included an import from JS, if it doesn't we should rename ours and move it to utils, something like eui-unique-id and replace JS usage with this

**Comment by nanuxbe** [comment]
Yes, polyfill sounds like a good idea if possible. If not possible at all, another option would be to have a breaking release and keep 5.10 for 3.28 and 6.x for 4.4+ but I'm not sure it's a good idea.

I'll try to take a bit of time to look at the natice `unique-id` and see how/if it can be imported directly in js.

**Comment by betocantu93** [comment]
Yea that should be another way, a breaking release, the problem would be to keep backporting any fixes or features in further versions, so until 3.28 is no longer LTS I would favor polyfill IMHO

**Comment by betocantu93** [comment]
@nanuxbe I end up pushing this [commit](https://github.com/prysmex/ember-eui/commit/ab5b8e25d1eee0f9e701ad762c87ae74ab91848d) forward, using guidFor for JS and also the polyfill, it should be fixed in `v5.10.2`

**Comment by betocantu93** [comment]
Please let me know if anything else is stopping you, thanks for reporting!

**Comment by nanuxbe** [comment]
Thanks. I'm not sure I will have time to test it this week but I'll try. Next week I'll be attending a conference, s it might be next month that you hear back from me

**Comment by betocantu93** [comment]
@nanuxbe have a great time on the conference!
