### ISSUE TITLE
Programatically use modal

### ISSUE THREAD

**Issue by IBRAHIMDANS** [prysmex/ember-eui#184]
Hello,

I would like to know if it's possible to use your modal programmatically, similar to the functionality provided by the library I mentioned.

[Link to the library: https://sethbrasile.github.io/ember-remodal/#/service]

**Comment by betocantu93** [comment]
Hey sorry I couldn't respond, it should be possible to do that if you make a wrapping component for EuiModal.

We just refactored the whole codebase to v2 addon. So let me know if you have doubts. I Can probably have a look at this on Tuesday. 

Maybe making another addon that implements ember promisable modals or ember modals manager Addons
