### ISSUE TITLE
Support Ember version 4.x

### ISSUE THREAD

**Issue by stefanhofmann2** [prysmex/ember-eui#81]
Using Ember version 4.1.1 in combination with ember-eui version 1.6 i get the following error:
reference error Ember is not defined. The error occurs in
define("@html-next/vertical-collection/components/vertical-collection/template", ["exports"], function (_exports) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.default = void 0;

  var _default = Ember.HTMLBars.template({
    "id": "BlT5dpw+",
    "block": "[[[42,[28,[37,1],[[28,[37,1],[[30,0,[\"virtualComponents\"]]],null]],null],\"id\",[[[1,[28,[35,2],[[30,1,[\"upperBound\"]]],null]],[41,[30,1,[\"isOccludedContent\"]],[[[2,[28,[37,2],[[30,1,[\"element\"]]],null]]],[]],[[[18,2,[[30,1,[\"content\"]],[30,1,[\"index\"]]]]],[]]],[1,[28,[35,2],[[30,1,[\"lowerBound\"]]],null]]],[1]],null],[1,\"\\n\"],[41,[30,0,[\"shouldYieldToInverse\"]],[[[1,\"  \"],[18,3,null],[1,\"\\n\"]],[]],null]],[\"virtualComponent\",\"&default\",\"&else\"],false,[\"each\",\"-track-array\",\"unbound\",\"if\",\"yield\"]]",
    "moduleName": "@html-next/vertical-collection/components/vertical-collection/template.hbs",
    "isStrictMode": false
  });
I am working on Windows 10 with nodejs version 16.13.
  _exports.default = _default;
});

**Comment by betocantu93** [comment]
Hello @stefanhofmann2 ! Thanks for opening this issue. I'll check this out soon enough. 

Are you using embroider? 

If so, could you _try_ adding the flag to the ember-svg-jar `hbs` strategy?

`bundle: false`

**Comment by betocantu93** [comment]
Already some work going on #82

**Comment by amiarSlimane** [comment]
Hello , for me i am getting the following error after installing ember-eui , my ember version is 4.1.0

```
Build Error (broccoli-persistent-filter:Babel > [Babel: @embroider/macros]) in @embroider/macros/runtime.js

/home/amiar/makane/promotion/admin-front/@embroider/macros/runtime.js: @babel/template placeholder "APP": Expected string substitution


Stack Trace and Error Report: /tmp/error.dump.858ad946bd20c92d54702d2f912a0283.log
```

**Comment by betocantu93** [comment]
Hello @amiarSlimane it seems the issue is related to an embroider version miss match please refer to the installation in the demo for instructions https://ember-eui.netlify.app/docs/installation

**Comment by amiarSlimane** [comment]
Thank you , i have used "override dependencies" as mentioned in the doc with a new fresh ember project , it is building successfully without errors, but i get the following error in the web browser console :

```
Uncaught ReferenceError: Ember is not defined
    <anonymous> template.js:9
    exports loader.js:106
    _reify loader.js:143
    reify loader.js:130
    exports loader.js:104
    _reify loader.js:143
    reify loader.js:130
    exports loader.js:104
    _reify loader.js:143
    reify loader.js:130
    exports loader.js:104
    requireModule loader.js:27
    r loader.js:176
    Ember 3
    <anonymous> app.js:26
    exports loader.js:106
    requireModule loader.js:27
    <anonymous> Ember

```
The error is in this line 
`var _default = Ember.HTMLBars.template({`

```
define("@html-next/vertical-collection/components/vertical-collection/template", ["exports"], function (_exports) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.default = void 0;

  var _default = Ember.HTMLBars.template({
    "id": "BlT5dpw+",
    "block": "[[[42,[28,[37,1],[[28,[37,1],[[30,0,[\"virtualComponents\"]]],null]],null],\"id\",[[[1,[28,[35,2],[[30,1,[\"upperBound\"]]],null]],[41,[30,1,[\"isOccludedContent\"]],[[[2,[28,[37,2],[[30,1,[\"element\"]]],null]]],[]],[[[18,2,[[30,1,[\"content\"]],[30,1,[\"index\"]]]]],[]]],[1,[28,[35,2],[[30,1,[\"lowerBound\"]]],null]]],[1]],null],[1,\"\\n\"],[41,[30,0,[\"shouldYieldToInverse\"]],[[[1,\"  \"],[18,3,null],[1,\"\\n\"]],[]],null]],[\"virtualComponent\",\"&default\",\"&else\"],false,[\"each\",\"-track-array\",\"unbound\",\"if\",\"yield\"]]",
    "moduleName": "@html-next/vertical-collection/components/vertical-collection/template.hbs",
    "isStrictMode": false
  });

  _exports.default = _default;
});
```

**Comment by betocantu93** [comment]
@stefanhofmann2 @amiarSlimane new version released, it _should_ now work with ember >v4.x.x , can you please confirm?

We had to depend on `html-next/vertical-collection#v3.0.0-0` in order to make it work, we should update this when they make a new stable release

**Comment by amiarSlimane** [comment]
Thank you @betocantu93  it is working.

**Comment by betocantu93** [comment]
@amiarSlimane great!
